services:
  - type: web
    name: rca-daily-report-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ariba_Daily_Analysis_report.py --server.port=$PORT --server.address=0.0.0.0